function escapeHtml(str) {
    if (str == null) return ''
    return String(str)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#x27;')
}

export function exportProgramToPDF(program) {
    const w = window.open('', '_blank')
    const html = `<!DOCTYPE html>
<html><head><title>${escapeHtml(program.name)} - Export</title>
<style>
body { font-family: 'Inter', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; }
h1 { font-size: 28px; margin-bottom: 4px; }
.meta { color: #666; font-size: 14px; margin-bottom: 24px; }
.desc { color: #444; line-height: 1.6; margin-bottom: 32px; }
table { width: 100%; border-collapse: collapse; }
th { text-align: left; padding: 12px 8px; border-bottom: 2px solid #FFD600; font-size: 12px; text-transform: uppercase; letter-spacing: .05em; color: #666; }
td { padding: 12px 8px; border-bottom: 1px solid #eee; font-size: 14px; }
.footer { margin-top: 40px; font-size: 12px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
.badge { display: inline-block; background: #FFD600; color: #000; font-size: 11px; font-weight: 700; padding: 3px 10px; border-radius: 9999px; margin-right: 8px; }
</style></head>
<body>
    <h1>${escapeHtml(program.name)}</h1>
    <div class="meta">
        <span class="badge">${escapeHtml(program.difficulty || 'All levels')}</span>
        ${escapeHtml(program.durationMinutes || '')} · ${escapeHtml(program.trainerName || 'FitPower')} · ${escapeHtml(program.weeks || '')} weeks
    </div>
    <p class="desc">${escapeHtml(program.description || '')}</p>
    <table>
        <thead><tr><th>Session</th><th>Type</th><th>Date</th><th>Time</th></tr></thead>
        <tbody>
            ${(program.sessions || []).map(s => `<tr>
                <td><strong>${escapeHtml(s.title)}</strong></td>
                <td>${escapeHtml(s.type || '—')}</td>
                <td>${escapeHtml(s.date || '—')}</td>
                <td>${escapeHtml(s.start_time ? s.start_time.substring(0, 5) : '—')}</td>
            </tr>`).join('')}
        </tbody>
    </table>
    <div class="footer">Generated by FitPower — Train Without Limits</div>
    <script>window.print()</script>
</body></html>`
    w.document.write(html)
    w.document.close()
}

export function exportRoutineToPDF(routine) {
    const w = window.open('', '_blank')
    const html = `<!DOCTYPE html>
<html><head><title>${escapeHtml(routine.title)} - Export</title>
<style>
body { font-family: 'Inter', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; }
h1 { font-size: 28px; margin-bottom: 4px; }
.meta { color: #666; font-size: 14px; margin-bottom: 24px; }
table { width: 100%; border-collapse: collapse; }
th { text-align: left; padding: 12px 8px; border-bottom: 2px solid #FFD600; font-size: 12px; text-transform: uppercase; letter-spacing: .05em; color: #666; }
td { padding: 12px 8px; border-bottom: 1px solid #eee; font-size: 14px; }
.num { width: 36px; height: 36px; background: #FFD600; border-radius: 8px; display: inline-flex; align-items: center; justify-content: center; font-weight: 700; font-size: 14px; margin-right: 12px; }
.footer { margin-top: 40px; font-size: 12px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
</style></head>
<body>
    <h1>${escapeHtml(routine.title)}</h1>
    <div class="meta">${escapeHtml(routine.duration_minutes || '0')} min · ${escapeHtml(routine.focus || '')} · ${escapeHtml(routine.difficulty || '')}</div>
    <table>
        <thead><tr><th>#</th><th>Exercise</th><th>Sets</th><th>Reps</th><th>Rest</th></tr></thead>
        <tbody>
            ${(routine.exercises || []).map((ex, i) => `<tr>
                <td>${i + 1}</td>
                <td><strong>${escapeHtml(ex.name)}</strong></td>
                <td>${escapeHtml(ex.sets || '—')}</td>
                <td>${escapeHtml(ex.reps || '—')}</td>
                <td>${escapeHtml(ex.rest || '—')}s</td>
            </tr>`).join('')}
        </tbody>
    </table>
    <div class="footer">Generated by FitPower — Train Without Limits</div>
    <script>window.print()</script>
</body></html>`
    w.document.write(html)
    w.document.close()
}

export function exportToCSV(data, filename = 'export.csv') {
    if (!data.length) return
    const headers = Object.keys(data[0])
    const csvContent = [
        headers.join(','),
        ...data.map(row => headers.map(h => {
            const val = row[h]
            if (val === null || val === undefined) return ''
            const str = String(val)
            if (str.includes(',') || str.includes('"') || str.includes('\n')) {
                return '"' + str.replace(/"/g, '""') + '"'
            }
            return str
        }).join(','))
    ].join('\n')

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
    const link = document.createElement('a')
    link.href = URL.createObjectURL(blob)
    link.download = filename
    link.click()
    URL.revokeObjectURL(link.href)
}

export function exportToPDF(title, data, columns) {
    const style = `
    <style>
        body { font-family: 'Inter', system-ui, sans-serif; padding: 40px; color: #111; }
        h1 { font-size: 24px; margin-bottom: 8px; color: #FFD600; }
        .subtitle { color: #666; margin-bottom: 24px; }
        table { width: 100%; border-collapse: collapse; }
        th { text-align: left; padding: 10px 12px; background: #f5f5f5; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: #666; border-bottom: 2px solid #eee; }
        td { padding: 10px 12px; border-bottom: 1px solid #eee; font-size: 14px; }
        tr:last-child td { border-bottom: none; }
        .footer { margin-top: 32px; font-size: 12px; color: #999; text-align: center; }
    </style>`

    const html = `
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"><title>${escapeHtml(title)}</title>${style}</head>
    <body>
        <h1>⚡ ${escapeHtml(title)}</h1>
        <p class="subtitle">Generated on ${new Date().toLocaleDateString()}</p>
        <table>
            <thead>
                <tr>${columns.map(c => `<th>${escapeHtml(c.label)}</th>`).join('')}</tr>
            </thead>
            <tbody>
                ${data.map(row => `<tr>${columns.map(c => `<td>${escapeHtml(row[c.key]) ?? '—'}</td>`).join('')}</tr>`).join('')}
            </tbody>
        </table>
        <div class="footer">FitPower — Train Without Limits</div>
        <script>window.print()</script>
    </body>
    </html>`

    const win = window.open('', '_blank')
    win.document.write(html)
    win.document.close()
}

export function exportProgressData(metrics) {
    if (!metrics?.length) return
    const columns = [
        { key: 'date', label: 'Date' },
        { key: 'weight', label: 'Weight (kg)' },
        { key: 'bodyFat', label: 'Body Fat (%)' },
        { key: 'muscle', label: 'Muscle Mass (kg)' },
        { key: 'bmi', label: 'BMI' },
    ]
    const data = metrics.map(m => ({
        date: m.created_at ? new Date(m.created_at).toLocaleDateString() : '—',
        weight: m.weight ?? '—',
        bodyFat: m.bodyFat ?? m.body_fat ?? '—',
        muscle: m.muscle ?? '—',
        bmi: m.bmi ?? '—',
    }))
    exportToPDF('Progress Report', data, columns)
}

export function exportWorkoutData(sessions) {
    if (!sessions?.length) return
    const columns = [
        { key: 'title', label: 'Workout' },
        { key: 'date', label: 'Date' },
        { key: 'type', label: 'Type' },
        { key: 'exercises', label: 'Exercises' },
        { key: 'status', label: 'Status' },
    ]
    const data = sessions.map(s => ({
        title: s.title || s.name || 'Workout',
        date: s.date ? new Date(s.date).toLocaleDateString() : '—',
        type: s.type || '—',
        exercises: Array.isArray(s.exercises) ? s.exercises.length : '—',
        status: s.status || '—',
    }))
    exportToPDF('Workout History', data, columns)
}
