ALTER TABLE articles ADD COLUMN is_featured TINYINT(1) DEFAULT 0;
ALTER TABLE articles ADD COLUMN is_archived TINYINT(1) DEFAULT 0;
ALTER TABLE articles ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
