ALTER TABLE forum_topics ADD COLUMN is_pinned TINYINT(1) DEFAULT 0;
ALTER TABLE forum_topics ADD COLUMN is_locked TINYINT(1) DEFAULT 0;
ALTER TABLE forum_topics ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
