CREATE TABLE IF NOT EXISTS user_nutrition_settings (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL UNIQUE,
    calories_target INT UNSIGNED NOT NULL DEFAULT 1940,
    protein_target DECIMAL(6,1) NOT NULL DEFAULT 150,
    carbs_target DECIMAL(6,1) NOT NULL DEFAULT 220,
    fat_target DECIMAL(6,1) NOT NULL DEFAULT 65,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
